In [78]:
import numpy as np
import random

In [2]:
array = np.random.randint(10, 99, size=(4, 3))
row_sum = array.sum(axis=1)
column_sum = 0
for col in array:
    column_sum +=col
total_sum = array.sum()
print (column_sum)
print (row_sum)
print (total_sum)
print (array)

[180 284 201]
[105 178 243 139]
665
[[14 72 19]
 [50 86 42]
 [79 84 80]
 [37 42 60]]


### Code Explanation

This code performs the following steps:

1. **Create a Random 4x3 Array**: 
   - A 4x3 array of random numbers between 10 and 98 is created.

2. **Sum of Each Row**: 
   - The sum of the numbers in each row of the array is calculated.

3. **Sum of Each Column**: 
   - A loop is used to calculate the sum of each column in the array.

4. **Total Sum of All Elements**: 
   - The sum of all the numbers in the entire array is calculated.

5. **Print Results**:
   - The program prints the sum of each column, the sum of each row, the total sum of all elements, and the array itself.

i also used multiple methods to calculate the sum, i did this because calculating the column with a for command is easy.


In [4]:
array = np.random.randint(0, 10, size=(10))
count = 0
for i in array:
    if i%2==0:
        count+=1
print (array)
print (count)

[4 6 5 1 4 3 9 0 1 0]
5


### Code Explanation

this simple code creates a single dimension array with range of 10.

i then simply count the amount of even numbers, for this case im including 0 as an even number.

In [29]:
array = np.arange(100)
reshape = array.reshape(10,10)
print ("base array")
print (array)
print ("reshaped array")
print (reshape)
copy_array = array.copy()
for i in copy_array:
    if i >50:
        copy_array[i] = -1
print ("new array with higher than 50 numbers replaced with -1")
print (copy_array)
sum = array.sum()
print (sum)
mean = array.mean()
print (mean)

base array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
reshaped array
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
new array with higher than 50 numbers replaced with -1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1


### simply i used existing methods to do all this.

### i added a text between the prints of the arrays becuase it was very hard to read without it.


In [62]:
array = np.array([10,20,30,40,50,60,70,80,90,100])
temp_array = np.array([], dtype=int)
print (array)
for i in array:
    if i <20 or i>50:
        temp_array = np.append(temp_array,i)
print (temp_array)
reshape = temp_array.reshape(2,3)
print (reshape)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  60  70  80  90 100]
[[ 10  60  70]
 [ 80  90 100]]


### i had to take a lot of liberties with the questions since i did not understand exactly what the question was asking.

in the base array i just made numbers from 10 to 100 since they have the same space between them, im not sure if the question asked for a random number or if the list even needs to reach 100 or if its just up to 100.

with this basis i simply created a temp array for the lower than 20 higher than 50, and a new array for the reshape which i assumed meant any shape for the array with the less than 20 more than 50, because its the only array that changes sizes.


In [92]:
array = np.zeros((4, 4), dtype=int)
array[0][0] = random.randint(0,100)
array[2][2] = random.randint(0,100)
array[3][3] = random.randint(0,100)
print(array)

[[37  0  0  0]
 [ 0  0  0  0]
 [ 0  0 54  0]
 [ 0  0  0 39]]
4
